Please open a free student account on Quandl: https://www.quandl.com/

You will have to access the data on continuous Eurodollar futures that is free in the CHRIS database:

https://www.quandl.com/data/CHRIS-Wiki-Continuous-Futures/documentation/introduction

Once you register, the access token will be auto-generated for your use in Python. Here is how your Python code will look like:

import quandl
token = "your_token_provided_by_Quandl"

n = range(1,21)
nms = ["CHRIS/CME_ED"+str(i) for i in n]

dfs = [quandl.get(nm, authtoken=token) for nm in nms]

This code will return an array of pandas data frames.  Note, that everyone should get an account on Quandl, so you should all have different access keys.

After you access the data, construct a single data frame with all Settle prices: Settle_ED1, Settle_ED2, ....

Write a short report summarizing the overall data set, its size, quality and gaps.

In [1]:
import quandl
import pandas as pd
token = "_K8DXUaWrH48p_sTaP2y"
n = range(1,21)
nms = ["CHRIS/CME_ED"+str(i) for i in n]

dfs = [quandl.get(nm, authtoken=token) for nm in nms]

In [33]:
Settle_df = pd.DataFrame({})

In [37]:
for i in range(len(dfs)):
    name = 'Settle_ED' + str(i + 1)
    Settle_df[name] = dfs[i]["Settle"]
Settle_df

,Settle_ED1,Settle_ED2,Settle_ED3,Settle_ED4,Settle_ED5,Settle_ED6,Settle_ED7,Settle_ED8,Settle_ED9,Settle_ED10,Settle_ED11,Settle_ED12,Settle_ED13,Settle_ED14,Settle_ED15,Settle_ED16,Settle_ED17,Settle_ED18,Settle_ED19,Settle_ED20
Date,,,,,,,,,,,,,,,,,,,,
1982-02-01,83.7400,83.690,83.690,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982-02-02,83.8800,83.850,83.850,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982-02-03,83.7300,83.890,83.910,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982-02-04,83.8500,83.930,83.910,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982-02-05,83.8500,83.930,83.910,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982-02-08,83.5800,83.730,83.730,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982-02-09,83.3900,83.640,83.800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982-02-10,83.5100,83.720,83.880,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982-02-11,83.4300,83.700,83.970,84.350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982-02-12,83.3600,83.640,83.980,84.350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982-02-16,83.2900,83.660,84.100,84.450,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982-02-17,83.4300,83.750,84.100,84.450,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982-02-18,84.0400,84.260,84.500,84.700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982-02-19,84.0000,84.250,84.480,84.750,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982-02-22,84.9900,85.080,85.230,85.550,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982-02-23,85.1300,85.060,85.100,85.400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982-02-24,85.3900,85.180,85.150,85.350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982-02-25,85.2000,85.060,85.190,85.270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982-02-26,84.8700,84.670,84.800,85.100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982-03-01,85.3300,85.150,85.180,85.300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982-03-02,85.3000,85.220,85.250,85.400,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982-03-03,85.3900,85.420,85.450,85.500,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982-03-04,85.4900,85.620,85.600,85.600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982-03-05,85.5300,85.610,85.570,85.700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982-03-08,85.6300,85.720,85.700,85.800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982-03-09,85.4000,85.440,85.440,85.630,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982-03-10,85.2800,85.300,85.410,85.550,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982-03-11,84.9900,85.010,85.150,85.350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982-03-12,84.8800,84.780,84.950,85.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1982-03-15,84.8800,84.740,84.870,85.030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2017-10-11,98.4850,98.355,98.255,98.180,98.095,98.045,98.000,97.965,97.910,97.885,97.855,97.825,97.780,97.755,97.720,97.685,97.640,97.610,97.575,97.535
2017-10-12,98.4900,98.360,98.255,98.180,98.100,98.050,98.010,97.975,97.920,97.895,97.870,97.840,97.795,97.770,97.735,97.700,97.655,97.630,97.595,97.560
2017-10-13,98.5050,98.375,98.275,98.205,98.125,98.080,98.040,98.010,97.960,97.935,97.910,97.885,97.840,97.815,97.785,97.750,97.705,97.680,97.645,97.610
2017-10-16,98.4950,98.350,98.235,98.150,98.065,98.015,97.970,97.940,97.890,97.870,97.850,97.825,97.780,97.760,97.730,97.700,97.660,97.635,97.605,97.570
2017-10-17,98.4900,98.350,98.235,98.150,98.060,98.005,97.960,97.925,97.875,97.855,97.835,97.810,97.770,97.750,97.720,97.690,97.650,97.630,97.600,97.565
2017-10-18,98.4900,98.350,98.235,98.145,98.055,97.995,97.945,97.905,97.850,97.830,97.805,97.780,97.735,97.715,97.685,97.650,97.610,97.585,97.555,97.520
2017-10-19,98.4950,98.360,98.250,98.165,98.080,98.020,97.965,97.925,97.870,97.845,97.820,97.795,97.750,97.725,97.695,97.665,97.620,97.595,97.565,97.530
2017-10-20,98.4900,98.350,98.235,98.150,98.055,97.990,97.935,97.890,97.830,97.800,97.770,97.740,97.695,97.665,97.630,97.595,97.555,97.530,97.495,97.455
2017-10-23,98.4950,98.360,98.250,98.165,98.075,98.010,97.955,97.910,97.850,97.820,97.790,97.760,97.715,97.685,97.650,97.615,97.570,97.545,97.510,97.470
2017-10-24,98.4900,98.355,98.245,98.160,98.070,98.005,97.945,97.895,97.835,97.805,97.770,97.735,97.690,97.660,97.625,97.585,97.540,97.510,97.475,97.435
2017-10-25,98.4900,98.345,98.225,98.140,98.045,97.975,97.915,97.865,97.805,97.770,97.735,97.700,97.650,97.615,97.580,97.540,97.495,97.465,97.425,97.385
2017-10-26,98.4850,98.340,98.220,98.130,98.035,97.965,97.900,97.850,97.785,97.755,97.720,97.685,97.640,97.610,97.575,97.535,97.490,97.460,97.425,97.385
2017-10-27,98.4850,98.350,98.235,98.150,98.055,97.990,97.930,97.880,97.820,97.790,97.755,97.720,97.675,97.645,97.610,97.570,97.525,97.495,97.460,97.420
2017-10-30,98.4900,98.360,98.250,98.170,98.085,98.025,97.970,97.925,97.870,97.840,97.810,97.780,97.735,97.705,97.670,97.635,97.590,97.560,97.525,97.485
2017-10-31,98.4900,98.350,98.235,98.155,98.075,98.020,97.965,97.920,97.865,97.835,97.805,97.775,97.730,97.700,97.665,97.630,97.585,97.560,97.525,97.485
2017-11-01,98.4850,98.335,98.215,98.135,98.055,98.000,97.950,97.905,97.850,97.825,97.795,97.760,97.715,97.685,97.650,97.615,97.570,97.545,97.510,97.475
2017-11-02,98.4850,98.340,98.225,98.150,98.075,98.020,97.970,97.930,97.875,97.850,97.820,97.790,97.745,97.715,97.685,97.650,97.605,97.580,97.545,97.510
2017-11-03,98.4800,98.330,98.215,98.140,98.065,98.010,97.955,97.915,97.865,97.840,97.815,97.785,97.740,97.715,97.685,97.650,97.610,97.585,97.555,97.520
2017-11-06,98.4750,98.330,98.215,98.140,98.070,98.020,97.975,97.935,97.885,97.860,97.835,97.810,97.770,97.740,97.710,97.680,97.640,97.615,97.585,97.555
2017-11-07,98.4650,98.320,98.205,98.135,98.065,98.015,97.970,97.935,97.885,97.860,97.835,97.810,97.770,97.745,97.715,97.685,97.645,97.625,97.600,97.565
2017-11-08,98.4600,98.320,98.205,98.130,98.060,98.010,97.965,97.930,97.880,97.855,97.830,97.805,97.760,97.735,97.705,97.675,97.635,97.615,97.585,97.555
2017-11-09,98.4700,98.325,98.210,98.140,98.070,98.020,97.975,97.935,97.885,97.860,97.835,97.805,97.760,97.735,97.705,97.670,97.630,97.605,97.575,97.540
2017-11-10,98.4650,98.310,98.190,98.115,98.040,97.985,97.935,97.895,97.840,97.810,97.780,97.750,97.700,97.670,97.635,97.600,97.555,97.530,97.495,97.460
2017-11-13,98.4675,98.300,98.175,98.095,98.010,97.955,97.905,97.860,97.805,97.780,97.755,97.725,97.680,97.655,97.625,97.595,97.550,97.525,97.495,97.465
2017-11-14,98.4675,98.300,98.175,98.095,98.015,97.960,97.910,97.870,97.820,97.795,97.770,97.740,97.695,97.670,97.640,97.610,97.565,97.540,97.515,97.480
2017-11-15,98.4675,98.310,98.185,98.110,98.035,97.985,97.940,97.905,97.855,97.830,97.805,97.780,97.740,97.715,97.685,97.655,97.620,97.600,97.570,97.540
2017-11-16,98.4625,98.295,98.160,98.080,98.005,97.955,97.905,97.870,97.820,97.795,97.770,97.745,97.700,97.675,97.650,97.620,97.580,97.560,97.535,97.505
2017-11-17,98.4575,98.295,98.160,98.080,98.010,97.960,97.910,97.875,97.825,97.805,97.780,97.755,97.710,97.685,97.660,97.630,97.590,97.570,97.545,97.515
2017-11-20,98.4500,98.275,98.135,98.045,97.970,97.920,97.875,97.840,97.790,97.770,97.745,97.720,97.680,97.655,97.630,97.600,97.565,97.545,97.520,97.490
2017-11-21,98.4475,98.265,98.115,98.025,97.950,97.895,97.845,97.810,97.765,97.745,97.725,97.700,97.660,97.640,97.620,97.600,97.565,97.550,97.530,97.505

In [42]:
Settle_df.describe()

,Settle_ED1,Settle_ED2,Settle_ED3,Settle_ED4,Settle_ED5,Settle_ED6,Settle_ED7,Settle_ED8,Settle_ED9,Settle_ED10,Settle_ED11,Settle_ED12,Settle_ED13,Settle_ED14,Settle_ED15,Settle_ED16,Settle_ED17,Settle_ED18,Settle_ED19,Settle_ED20
count,9010.000000,9008.000000,9008.000000,8973.000000,8591.000000,8574.000000,8356.000000,8315.000000,7645.000000,7641.000000,7574.000000,7510.000000,6886.000000,6820.000000,6758.000000,6693.000000,5924.000000,5858.000000,5795.000000,5729.000000
mean,95.392472,95.263189,95.108844,94.973249,95.105494,94.939890,94.980138,94.868203,95.122984,95.005099,94.890290,94.782868,95.018704,94.925971,94.808053,94.717203,95.058662,94.982644,94.948334,94.894580
std,3.420502,3.475737,3.502251,3.469477,3.178593,3.170416,2.935718,2.884006,2.604536,2.572592,2.551129,2.528868,2.288377,2.268641,2.719474,2.707827,2.537735,2.536198,1.910141,1.896135
min,83.290000,83.640000,83.690000,83.970000,84.850000,84.550000,86.180000,86.870000,89.250000,89.160000,89.080000,89.000000,90.280000,90.270000,6.045000,5.870000,5.700000,5.565000,91.310000,91.260000
25%,93.320000,93.180000,92.980000,92.810000,93.080000,92.910000,92.950000,92.830000,93.250000,93.180000,93.100000,93.001250,93.270000,93.200000,93.145000,93.090000,93.450000,93.370000,93.320000,93.255000
50%,94.995000,95.042500,95.045000,94.975000,95.085000,94.975000,94.910000,94.750000,94.905000,94.840000,94.745000,94.630000,94.867500,94.780000,94.697500,94.590000,94.920000,94.880000,94.850000,94.830000
75%,98.775000,98.685000,98.515000,98.375000,98.260000,98.030000,97.850000,97.590000,97.635000,97.435000,97.240000,97.058750,97.233750,97.085000,96.925000,96.790000,96.880000,96.760000,96.655000,96.570000
max,99.780000,99.770000,99.755000,99.750000,99.750000,99.740000,99.730000,99.680000,99.585000,99.465000,99.405000,99.325000,99.220000,99.110000,98.980000,98.845000,98.760000,98.705000,98.655000,98.605000

Mean prices of all depth prices are pretty smooth, but standard deviations has decreasing trend (in general) as depth becomes greater.

Also as depth increases, the size of dataset decreases.